// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { MergeLink } from '../../../userlib/initialize.js';
// END EXTRA CODE

/**
 * @param {string} linkToken
 * @returns {Promise.<string>}
 */
export async function InitiateLinkingFlow(linkToken) {
	// BEGIN USER CODE
	return new Promise(function(resolve, reject) {
		window.MergeLink.initialize({
			linkToken: linkToken,
			onSuccess: (public_token) => resolve(public_token),
			onFailure: (event) => reject(event.error),
		});

		window.MergeLink.openLink();
	});
	// END USER CODE
}
