// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
function onSuccess(public_token) {
	return public_token;
}
// END EXTRA CODE

/**
 * @param {string} linkToken
 * @returns {Promise.<string>}
 */
export async function InitiateLinkingFlow(linkToken) {
	// BEGIN USER CODE
	MergeLink.initialize({
		linkToken: linkToken,
		onSuccess: (public_token) => onSuccess(public_token),
	});

	MergeLink.openLink();

	return onSuccess().resolve();
	// END USER CODE
}
