// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package merge.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GenerateLinkToken extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __configuration;
	private merge.proxies.Configuration configuration;

	public GenerateLinkToken(IContext context, IMendixObject configuration)
	{
		super(context);
		this.__configuration = configuration;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.configuration = __configuration == null ? null : merge.proxies.Configuration.initialize(getContext(), __configuration);

		// BEGIN USER CODE
		return createLinkToken(this.configuration);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateLinkToken";
	}

	// BEGIN EXTRA CODE
	/**
	 * @see "https://www.merge.dev/docs/linking-flow/get-started"
	 * @return link_token
	 */
	private static String createLinkToken(merge.proxies.Configuration configuration)
			throws IOException, InterruptedException, CoreException {
		return createLinkToken(configuration.getOrganizationId(),
				configuration.getOrganizationName(),
				configuration.getEmailAddress(),
				configuration.getCategory_hris(),
				configuration.getCategory_ats(),
				configuration.getCategory_accounting(),
				configuration.getIntegration(),
				configuration.getAPIKey());
	}

	static String createLinkToken(String organizationId, String organizationName, String emailAddress, boolean categoryHris, boolean categoryAts, boolean categoryAccounting, String integration, String apiKey) throws IOException, InterruptedException {
		Map<Object, Object> data = new HashMap();
		data.put("end_user_origin_id", organizationId);
		data.put("end_user_organization_name", organizationName);
		data.put("end_user_email_address", emailAddress);
		List<String> categories = new ArrayList<>();
		if (categoryHris) {
			categories.add("hris");
		}
		if (categoryAts) {
			categories.add("ats");
		}
		if (categoryAccounting) {
			categories.add("accounting");
		}
		data.put("categories", categories.toArray(String[]::new));
		if (integration != null && !"".equals(integration.trim())) {
			data.put("integration", integration);
		}
		ObjectMapper mapper = new ObjectMapper();
		String requestBody = mapper.writeValueAsString(data);

		HttpClient client = HttpClient.newHttpClient();
		URI uri = URI.create("https://api.merge.dev/api/integrations/create-link-token");
		HttpRequest request = HttpRequest.newBuilder(uri)
                .header("Content-Type", "application/json")
                .header("Authorization", String.format("Bearer %s", apiKey))
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .build();

		HttpResponse<String> linkTokenResult = client.send(request, HttpResponse.BodyHandlers.ofString());
		ObjectNode jsonNodes = new ObjectMapper().readValue(linkTokenResult.body(), ObjectNode.class);
		String linkToken = jsonNodes.get("link_token").textValue();
		return linkToken;
	}
	// END EXTRA CODE
}
