// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package merge.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import merge.proxies.GetEmployeesParam;
import merge.proxies.GetEmployeesResult;
import merge_hris_client.ApiClient;
import merge_hris_client.ApiException;
import merge_hris_client.Configuration;
import merge_hris_client.auth.*;
import merge_hris_client.model.*;
import merge_hris_client.api.EmployeesApi;
import org.threeten.bp.OffsetDateTime;
import java.util.logging.Logger;

public class GetEmployees extends CustomJavaAction<IMendixObject>
{
	private java.lang.String accountToken;
	private java.lang.String apiKey;
	private IMendixObject __params;
	private merge.proxies.GetEmployeesParam params;

	public GetEmployees(IContext context, java.lang.String accountToken, java.lang.String apiKey, IMendixObject params)
	{
		super(context);
		this.accountToken = accountToken;
		this.apiKey = apiKey;
		this.__params = params;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.params = __params == null ? null : merge.proxies.GetEmployeesParam.initialize(getContext(), __params);

		// BEGIN USER CODE
		PaginatedEmployeeList result = getEmployees(apiKey, accountToken, params);
		GetEmployeesResult mxResult = new GetEmployeesResult(getContext());
		mxResult.setNext(result.getNext());
		mxResult.setPrevious(result.getPrevious());
		for (Employee employee : result.getResults()) {
			merge.proxies.Employee mxEmployee = new merge.proxies.Employee(getContext());
			mxEmployee.set_Id(employee.getId().toString());
			mxEmployee.setFirstName(employee.getFirstName());
			mxEmployee.setLastName(employee.getLastName());
			mxEmployee.setDisplayFullName(employee.getDisplayFullName());
			mxResult.getGetEmployeesResult_Employee().add(mxEmployee);
		}
		return mxResult.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetEmployees";
	}

	// BEGIN EXTRA CODE
	private static Logger logger = Logger.getLogger("GetEmployees");

	private static PaginatedEmployeeList getEmployees(String apiKey, String accountToken, GetEmployeesParam params) throws Exception {
		ApiClient defaultClient = Configuration.getDefaultApiClient();
		defaultClient.setBasePath("https://api.merge.dev/api/hris/v1");

		// Configure API key authorization: tokenAuth
		ApiKeyAuth tokenAuth = (ApiKeyAuth) defaultClient.getAuthentication("tokenAuth");
		tokenAuth.setApiKey(apiKey);
		// Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
		tokenAuth.setApiKeyPrefix("Bearer");

		EmployeesApi apiInstance = new EmployeesApi(defaultClient);
		String xAccountToken = accountToken; // String | Token identifying the end user.
		String companyId = null; // String | If provided, will only return employees for this company.
		OffsetDateTime createdAfter = null; // OffsetDateTime | If provided, will only return objects created after this datetime.
		OffsetDateTime createdBefore = null; // OffsetDateTime | If provided, will only return objects created before this datetime.
		String cursor = null; // String | The pagination cursor value.
		Boolean includeRemoteData = null; // Boolean | Whether to include the original data Merge fetched from the third-party to produce these models.
		Boolean includeSensitiveFields = null; // Boolean | Whether to include sensetive fields (such as social security numbers) in the response.
		String managerId = null; // String | If provided, will only return employees for this manager.
		OffsetDateTime modifiedAfter = null; // OffsetDateTime | If provided, will only return objects modified after this datetime.
		OffsetDateTime modifiedBefore = null; // OffsetDateTime | If provided, will only return objects modified before this datetime.
		Integer pageSize = null; // Integer | Number of results to return per page.
		String remoteId = null; // String | The API provider's ID for the given object.
		String teamId = null; // String | If provided, will only return employees for this team.
		String workLocationId = null; // String | If provided, will only return employees for this location.
		try {
			PaginatedEmployeeList result = apiInstance.employeesList(xAccountToken, companyId, createdAfter, createdBefore, cursor, includeRemoteData, includeSensitiveFields, managerId, modifiedAfter, modifiedBefore, pageSize, remoteId, teamId, workLocationId);
			logger.info(String.valueOf("result : " + result));
			return result;
		} catch (ApiException e) {
			logger.severe("Exception when calling EmployeesApi#employeesList");
			logger.severe("Status code: " + e.getCode());
			logger.severe("Reason: " + e.getResponseBody());
			logger.severe("Response headers: " + e.getResponseHeaders());
			throw new Exception("xception when calling EmployeesApi#employeesList : " + e.getCode() + " / " + e.getResponseBody(), e);
		}
	}
	// END EXTRA CODE
}
