// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class EmployeesListParams extends merge.proxies.QueryParams
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.EmployeesListParams";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CompanyId("CompanyId"),
		IncludeSensitiveFields("IncludeSensitiveFields"),
		ManagerId("ManagerId"),
		TeamId("TeamId"),
		WorkLocationId("WorkLocationId"),
		AccountToken("AccountToken"),
		CreatedAfter("CreatedAfter"),
		CreatedBefore("CreatedBefore"),
		Cursor("Cursor"),
		IncludeRemoteData("IncludeRemoteData"),
		ModifiedAfter("ModifiedAfter"),
		ModifiedBefore("ModifiedBefore"),
		PageSize("PageSize"),
		RemoteId("RemoteId");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeesListParams(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.EmployeesListParams"));
	}

	protected EmployeesListParams(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeesListParamsMendixObject)
	{
		super(context, employeesListParamsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.EmployeesListParams", employeesListParamsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.EmployeesListParams");
	}

	/**
	 * @deprecated Use 'EmployeesListParams.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.EmployeesListParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.EmployeesListParams.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.EmployeesListParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.EmployeesListParams(context, mendixObject);
	}

	public static merge.proxies.EmployeesListParams load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.EmployeesListParams.initialize(context, mendixObject);
	}

	/**
	 * @return value of CompanyId
	 */
	public final java.lang.String getCompanyId()
	{
		return getCompanyId(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyId
	 */
	public final java.lang.String getCompanyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyId.toString());
	}

	/**
	 * Set value of CompanyId
	 * @param companyid
	 */
	public final void setCompanyId(java.lang.String companyid)
	{
		setCompanyId(getContext(), companyid);
	}

	/**
	 * Set value of CompanyId
	 * @param context
	 * @param companyid
	 */
	public final void setCompanyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyid)
	{
		getMendixObject().setValue(context, MemberNames.CompanyId.toString(), companyid);
	}

	/**
	 * Set value of IncludeSensitiveFields
	 * @param includesensitivefields
	 */
	public final merge.proxies.NullableBoolean getIncludeSensitiveFields()
	{
		return getIncludeSensitiveFields(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeSensitiveFields
	 */
	public final merge.proxies.NullableBoolean getIncludeSensitiveFields(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.IncludeSensitiveFields.toString());
		if (obj == null)
			return null;

		return merge.proxies.NullableBoolean.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of IncludeSensitiveFields
	 * @param includesensitivefields
	 */
	public final void setIncludeSensitiveFields(merge.proxies.NullableBoolean includesensitivefields)
	{
		setIncludeSensitiveFields(getContext(), includesensitivefields);
	}

	/**
	 * Set value of IncludeSensitiveFields
	 * @param context
	 * @param includesensitivefields
	 */
	public final void setIncludeSensitiveFields(com.mendix.systemwideinterfaces.core.IContext context, merge.proxies.NullableBoolean includesensitivefields)
	{
		if (includesensitivefields != null)
			getMendixObject().setValue(context, MemberNames.IncludeSensitiveFields.toString(), includesensitivefields.toString());
		else
			getMendixObject().setValue(context, MemberNames.IncludeSensitiveFields.toString(), null);
	}

	/**
	 * @return value of ManagerId
	 */
	public final java.lang.String getManagerId()
	{
		return getManagerId(getContext());
	}

	/**
	 * @param context
	 * @return value of ManagerId
	 */
	public final java.lang.String getManagerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ManagerId.toString());
	}

	/**
	 * Set value of ManagerId
	 * @param managerid
	 */
	public final void setManagerId(java.lang.String managerid)
	{
		setManagerId(getContext(), managerid);
	}

	/**
	 * Set value of ManagerId
	 * @param context
	 * @param managerid
	 */
	public final void setManagerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String managerid)
	{
		getMendixObject().setValue(context, MemberNames.ManagerId.toString(), managerid);
	}

	/**
	 * @return value of TeamId
	 */
	public final java.lang.String getTeamId()
	{
		return getTeamId(getContext());
	}

	/**
	 * @param context
	 * @return value of TeamId
	 */
	public final java.lang.String getTeamId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TeamId.toString());
	}

	/**
	 * Set value of TeamId
	 * @param teamid
	 */
	public final void setTeamId(java.lang.String teamid)
	{
		setTeamId(getContext(), teamid);
	}

	/**
	 * Set value of TeamId
	 * @param context
	 * @param teamid
	 */
	public final void setTeamId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teamid)
	{
		getMendixObject().setValue(context, MemberNames.TeamId.toString(), teamid);
	}

	/**
	 * @return value of WorkLocationId
	 */
	public final java.lang.String getWorkLocationId()
	{
		return getWorkLocationId(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkLocationId
	 */
	public final java.lang.String getWorkLocationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkLocationId.toString());
	}

	/**
	 * Set value of WorkLocationId
	 * @param worklocationid
	 */
	public final void setWorkLocationId(java.lang.String worklocationid)
	{
		setWorkLocationId(getContext(), worklocationid);
	}

	/**
	 * Set value of WorkLocationId
	 * @param context
	 * @param worklocationid
	 */
	public final void setWorkLocationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String worklocationid)
	{
		getMendixObject().setValue(context, MemberNames.WorkLocationId.toString(), worklocationid);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.EmployeesListParams that = (merge.proxies.EmployeesListParams) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.EmployeesListParams";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
