// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class EmployeesListResult extends merge.proxies.QueryResult
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.EmployeesListResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Next("Next"),
		Previous("Previous"),
		EmployeesListResult_Employee("Merge.EmployeesListResult_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeesListResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.EmployeesListResult"));
	}

	protected EmployeesListResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeesListResultMendixObject)
	{
		super(context, employeesListResultMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.EmployeesListResult", employeesListResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.EmployeesListResult");
	}

	/**
	 * @deprecated Use 'EmployeesListResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.EmployeesListResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.EmployeesListResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.EmployeesListResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.EmployeesListResult(context, mendixObject);
	}

	public static merge.proxies.EmployeesListResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.EmployeesListResult.initialize(context, mendixObject);
	}

	/**
	 * @return value of EmployeesListResult_Employee
	 */
	public final java.util.List<merge.proxies.Employee> getEmployeesListResult_Employee() throws com.mendix.core.CoreException
	{
		return getEmployeesListResult_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeesListResult_Employee
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<merge.proxies.Employee> getEmployeesListResult_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<merge.proxies.Employee> result = new java.util.ArrayList<merge.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.EmployeesListResult_Employee.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(merge.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of EmployeesListResult_Employee
	 * @param employeeslistresult_employee
	 */
	public final void setEmployeesListResult_Employee(java.util.List<merge.proxies.Employee> employeeslistresult_employee)
	{
		setEmployeesListResult_Employee(getContext(), employeeslistresult_employee);
	}

	/**
	 * Set value of EmployeesListResult_Employee
	 * @param context
	 * @param employeeslistresult_employee
	 */
	public final void setEmployeesListResult_Employee(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<merge.proxies.Employee> employeeslistresult_employee)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (merge.proxies.Employee proxyObject : employeeslistresult_employee)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.EmployeesListResult_Employee.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.EmployeesListResult that = (merge.proxies.EmployeesListResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.EmployeesListResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
