// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class Employee extends merge.proxies.Entity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmployeeNumber("EmployeeNumber"),
		Company("Company"),
		FirstName("FirstName"),
		LastName("LastName"),
		DisplayFullName("DisplayFullName"),
		WorkEmail("WorkEmail"),
		PersonalEmail("PersonalEmail"),
		MobilePhoneNumber("MobilePhoneNumber"),
		HomeLocation("HomeLocation"),
		_Id("_Id"),
		RemoteId("RemoteId"),
		Entity_RemoteData("Merge.Entity_RemoteData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.Employee"));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		super(context, employeeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.Employee", employeeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.Employee");
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.Employee(context, mendixObject);
	}

	public static merge.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.Employee.initialize(context, mendixObject);
	}

	/**
	 * @return value of EmployeeNumber
	 */
	public final java.lang.String getEmployeeNumber()
	{
		return getEmployeeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeNumber
	 */
	public final java.lang.String getEmployeeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeNumber.toString());
	}

	/**
	 * Set value of EmployeeNumber
	 * @param employeenumber
	 */
	public final void setEmployeeNumber(java.lang.String employeenumber)
	{
		setEmployeeNumber(getContext(), employeenumber);
	}

	/**
	 * Set value of EmployeeNumber
	 * @param context
	 * @param employeenumber
	 */
	public final void setEmployeeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeenumber)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeNumber.toString(), employeenumber);
	}

	/**
	 * @return value of Company
	 */
	public final java.lang.String getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final java.lang.String getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(java.lang.String company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of DisplayFullName
	 */
	public final java.lang.String getDisplayFullName()
	{
		return getDisplayFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayFullName
	 */
	public final java.lang.String getDisplayFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayFullName.toString());
	}

	/**
	 * Set value of DisplayFullName
	 * @param displayfullname
	 */
	public final void setDisplayFullName(java.lang.String displayfullname)
	{
		setDisplayFullName(getContext(), displayfullname);
	}

	/**
	 * Set value of DisplayFullName
	 * @param context
	 * @param displayfullname
	 */
	public final void setDisplayFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayfullname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayFullName.toString(), displayfullname);
	}

	/**
	 * @return value of WorkEmail
	 */
	public final java.lang.String getWorkEmail()
	{
		return getWorkEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkEmail
	 */
	public final java.lang.String getWorkEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkEmail.toString());
	}

	/**
	 * Set value of WorkEmail
	 * @param workemail
	 */
	public final void setWorkEmail(java.lang.String workemail)
	{
		setWorkEmail(getContext(), workemail);
	}

	/**
	 * Set value of WorkEmail
	 * @param context
	 * @param workemail
	 */
	public final void setWorkEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workemail)
	{
		getMendixObject().setValue(context, MemberNames.WorkEmail.toString(), workemail);
	}

	/**
	 * @return value of PersonalEmail
	 */
	public final java.lang.String getPersonalEmail()
	{
		return getPersonalEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonalEmail
	 */
	public final java.lang.String getPersonalEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PersonalEmail.toString());
	}

	/**
	 * Set value of PersonalEmail
	 * @param personalemail
	 */
	public final void setPersonalEmail(java.lang.String personalemail)
	{
		setPersonalEmail(getContext(), personalemail);
	}

	/**
	 * Set value of PersonalEmail
	 * @param context
	 * @param personalemail
	 */
	public final void setPersonalEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String personalemail)
	{
		getMendixObject().setValue(context, MemberNames.PersonalEmail.toString(), personalemail);
	}

	/**
	 * @return value of MobilePhoneNumber
	 */
	public final java.lang.String getMobilePhoneNumber()
	{
		return getMobilePhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MobilePhoneNumber
	 */
	public final java.lang.String getMobilePhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MobilePhoneNumber.toString());
	}

	/**
	 * Set value of MobilePhoneNumber
	 * @param mobilephonenumber
	 */
	public final void setMobilePhoneNumber(java.lang.String mobilephonenumber)
	{
		setMobilePhoneNumber(getContext(), mobilephonenumber);
	}

	/**
	 * Set value of MobilePhoneNumber
	 * @param context
	 * @param mobilephonenumber
	 */
	public final void setMobilePhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mobilephonenumber)
	{
		getMendixObject().setValue(context, MemberNames.MobilePhoneNumber.toString(), mobilephonenumber);
	}

	/**
	 * @return value of HomeLocation
	 */
	public final java.lang.String getHomeLocation()
	{
		return getHomeLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of HomeLocation
	 */
	public final java.lang.String getHomeLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HomeLocation.toString());
	}

	/**
	 * Set value of HomeLocation
	 * @param homelocation
	 */
	public final void setHomeLocation(java.lang.String homelocation)
	{
		setHomeLocation(getContext(), homelocation);
	}

	/**
	 * Set value of HomeLocation
	 * @param context
	 * @param homelocation
	 */
	public final void setHomeLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String homelocation)
	{
		getMendixObject().setValue(context, MemberNames.HomeLocation.toString(), homelocation);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.Employee that = (merge.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.Employee";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
