// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class GetEmployeesResult extends merge.proxies.QueryResult
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.GetEmployeesResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Next("Next"),
		Previous("Previous"),
		GetEmployeesResult_Employee("Merge.GetEmployeesResult_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetEmployeesResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.GetEmployeesResult"));
	}

	protected GetEmployeesResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getEmployeesResultMendixObject)
	{
		super(context, getEmployeesResultMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.GetEmployeesResult", getEmployeesResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.GetEmployeesResult");
	}

	/**
	 * @deprecated Use 'GetEmployeesResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.GetEmployeesResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.GetEmployeesResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.GetEmployeesResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.GetEmployeesResult(context, mendixObject);
	}

	public static merge.proxies.GetEmployeesResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.GetEmployeesResult.initialize(context, mendixObject);
	}

	/**
	 * @return value of GetEmployeesResult_Employee
	 */
	public final java.util.List<merge.proxies.Employee> getGetEmployeesResult_Employee() throws com.mendix.core.CoreException
	{
		return getGetEmployeesResult_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of GetEmployeesResult_Employee
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<merge.proxies.Employee> getGetEmployeesResult_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<merge.proxies.Employee> result = new java.util.ArrayList<merge.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GetEmployeesResult_Employee.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(merge.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GetEmployeesResult_Employee
	 * @param getemployeesresult_employee
	 */
	public final void setGetEmployeesResult_Employee(java.util.List<merge.proxies.Employee> getemployeesresult_employee)
	{
		setGetEmployeesResult_Employee(getContext(), getemployeesresult_employee);
	}

	/**
	 * Set value of GetEmployeesResult_Employee
	 * @param context
	 * @param getemployeesresult_employee
	 */
	public final void setGetEmployeesResult_Employee(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<merge.proxies.Employee> getemployeesresult_employee)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (merge.proxies.Employee proxyObject : getemployeesresult_employee)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GetEmployeesResult_Employee.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.GetEmployeesResult that = (merge.proxies.GetEmployeesResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.GetEmployeesResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
