// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class PaginatedLocationList
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paginatedLocationListMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.PaginatedLocationList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Next("Next"),
		Previous("Previous");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaginatedLocationList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.PaginatedLocationList"));
	}

	protected PaginatedLocationList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paginatedLocationListMendixObject)
	{
		if (paginatedLocationListMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Merge.PaginatedLocationList", paginatedLocationListMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.PaginatedLocationList");

		this.paginatedLocationListMendixObject = paginatedLocationListMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PaginatedLocationList.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.PaginatedLocationList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.PaginatedLocationList.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.PaginatedLocationList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.PaginatedLocationList(context, mendixObject);
	}

	public static merge.proxies.PaginatedLocationList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.PaginatedLocationList.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Next
	 */
	public final java.lang.String getNext()
	{
		return getNext(getContext());
	}

	/**
	 * @param context
	 * @return value of Next
	 */
	public final java.lang.String getNext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Next.toString());
	}

	/**
	 * Set value of Next
	 * @param next
	 */
	public final void setNext(java.lang.String next)
	{
		setNext(getContext(), next);
	}

	/**
	 * Set value of Next
	 * @param context
	 * @param next
	 */
	public final void setNext(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String next)
	{
		getMendixObject().setValue(context, MemberNames.Next.toString(), next);
	}

	/**
	 * @return value of Previous
	 */
	public final java.lang.String getPrevious()
	{
		return getPrevious(getContext());
	}

	/**
	 * @param context
	 * @return value of Previous
	 */
	public final java.lang.String getPrevious(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Previous.toString());
	}

	/**
	 * Set value of Previous
	 * @param previous
	 */
	public final void setPrevious(java.lang.String previous)
	{
		setPrevious(getContext(), previous);
	}

	/**
	 * Set value of Previous
	 * @param context
	 * @param previous
	 */
	public final void setPrevious(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String previous)
	{
		getMendixObject().setValue(context, MemberNames.Previous.toString(), previous);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paginatedLocationListMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.PaginatedLocationList that = (merge.proxies.PaginatedLocationList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.PaginatedLocationList";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
