// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class PaginatedTeamList extends merge.proxies.PaginatedList
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.PaginatedTeamList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Next("Next"),
		Previous("Previous"),
		PaginatedTeamList_Team("Merge.PaginatedTeamList_Team");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaginatedTeamList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.PaginatedTeamList"));
	}

	protected PaginatedTeamList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paginatedTeamListMendixObject)
	{
		super(context, paginatedTeamListMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.PaginatedTeamList", paginatedTeamListMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.PaginatedTeamList");
	}

	/**
	 * @deprecated Use 'PaginatedTeamList.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.PaginatedTeamList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.PaginatedTeamList.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.PaginatedTeamList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.PaginatedTeamList(context, mendixObject);
	}

	public static merge.proxies.PaginatedTeamList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.PaginatedTeamList.initialize(context, mendixObject);
	}

	/**
	 * @return value of PaginatedTeamList_Team
	 */
	public final java.util.List<merge.proxies.Team> getPaginatedTeamList_Team() throws com.mendix.core.CoreException
	{
		return getPaginatedTeamList_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of PaginatedTeamList_Team
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<merge.proxies.Team> getPaginatedTeamList_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<merge.proxies.Team> result = new java.util.ArrayList<merge.proxies.Team>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PaginatedTeamList_Team.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(merge.proxies.Team.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of PaginatedTeamList_Team
	 * @param paginatedteamlist_team
	 */
	public final void setPaginatedTeamList_Team(java.util.List<merge.proxies.Team> paginatedteamlist_team)
	{
		setPaginatedTeamList_Team(getContext(), paginatedteamlist_team);
	}

	/**
	 * Set value of PaginatedTeamList_Team
	 * @param context
	 * @param paginatedteamlist_team
	 */
	public final void setPaginatedTeamList_Team(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<merge.proxies.Team> paginatedteamlist_team)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (merge.proxies.Team proxyObject : paginatedteamlist_team)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.PaginatedTeamList_Team.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.PaginatedTeamList that = (merge.proxies.PaginatedTeamList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.PaginatedTeamList";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
