// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class PaginatedLocationList extends merge.proxies.PaginatedList
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.PaginatedLocationList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Next("Next"),
		Previous("Previous"),
		PaginatedLocationList_Location("Merge.PaginatedLocationList_Location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaginatedLocationList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.PaginatedLocationList"));
	}

	protected PaginatedLocationList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paginatedLocationListMendixObject)
	{
		super(context, paginatedLocationListMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Merge.PaginatedLocationList", paginatedLocationListMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.PaginatedLocationList");
	}

	/**
	 * @deprecated Use 'PaginatedLocationList.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.PaginatedLocationList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.PaginatedLocationList.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.PaginatedLocationList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.PaginatedLocationList(context, mendixObject);
	}

	public static merge.proxies.PaginatedLocationList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.PaginatedLocationList.initialize(context, mendixObject);
	}

	/**
	 * @return value of PaginatedLocationList_Location
	 */
	public final java.util.List<merge.proxies.Location> getPaginatedLocationList_Location() throws com.mendix.core.CoreException
	{
		return getPaginatedLocationList_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of PaginatedLocationList_Location
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<merge.proxies.Location> getPaginatedLocationList_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<merge.proxies.Location> result = new java.util.ArrayList<merge.proxies.Location>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PaginatedLocationList_Location.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(merge.proxies.Location.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of PaginatedLocationList_Location
	 * @param paginatedlocationlist_location
	 */
	public final void setPaginatedLocationList_Location(java.util.List<merge.proxies.Location> paginatedlocationlist_location)
	{
		setPaginatedLocationList_Location(getContext(), paginatedlocationlist_location);
	}

	/**
	 * Set value of PaginatedLocationList_Location
	 * @param context
	 * @param paginatedlocationlist_location
	 */
	public final void setPaginatedLocationList_Location(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<merge.proxies.Location> paginatedlocationlist_location)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (merge.proxies.Location proxyObject : paginatedlocationlist_location)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.PaginatedLocationList_Location.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.PaginatedLocationList that = (merge.proxies.PaginatedLocationList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.PaginatedLocationList";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
