// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class QueryParams
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject queryParamsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.QueryParams";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreatedAfter("CreatedAfter"),
		CreatedBefore("CreatedBefore"),
		Cursor("Cursor"),
		IncludeRemoteData("IncludeRemoteData"),
		ModifiedAfter("ModifiedAfter"),
		ModifiedBefore("ModifiedBefore"),
		PageSize("PageSize"),
		RemoteId("RemoteId");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QueryParams(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.QueryParams"));
	}

	protected QueryParams(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject queryParamsMendixObject)
	{
		if (queryParamsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Merge.QueryParams", queryParamsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.QueryParams");

		this.queryParamsMendixObject = queryParamsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'QueryParams.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.QueryParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.QueryParams.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.QueryParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Merge.GetEmployeesParam", mendixObject.getType()))
			return merge.proxies.GetEmployeesParam.initialize(context, mendixObject);

		return new merge.proxies.QueryParams(context, mendixObject);
	}

	public static merge.proxies.QueryParams load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.QueryParams.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreatedAfter
	 */
	public final java.util.Date getCreatedAfter()
	{
		return getCreatedAfter(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAfter
	 */
	public final java.util.Date getCreatedAfter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedAfter.toString());
	}

	/**
	 * Set value of CreatedAfter
	 * @param createdafter
	 */
	public final void setCreatedAfter(java.util.Date createdafter)
	{
		setCreatedAfter(getContext(), createdafter);
	}

	/**
	 * Set value of CreatedAfter
	 * @param context
	 * @param createdafter
	 */
	public final void setCreatedAfter(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdafter)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAfter.toString(), createdafter);
	}

	/**
	 * @return value of CreatedBefore
	 */
	public final java.util.Date getCreatedBefore()
	{
		return getCreatedBefore(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedBefore
	 */
	public final java.util.Date getCreatedBefore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedBefore.toString());
	}

	/**
	 * Set value of CreatedBefore
	 * @param createdbefore
	 */
	public final void setCreatedBefore(java.util.Date createdbefore)
	{
		setCreatedBefore(getContext(), createdbefore);
	}

	/**
	 * Set value of CreatedBefore
	 * @param context
	 * @param createdbefore
	 */
	public final void setCreatedBefore(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdbefore)
	{
		getMendixObject().setValue(context, MemberNames.CreatedBefore.toString(), createdbefore);
	}

	/**
	 * @return value of Cursor
	 */
	public final java.lang.String getCursor()
	{
		return getCursor(getContext());
	}

	/**
	 * @param context
	 * @return value of Cursor
	 */
	public final java.lang.String getCursor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cursor.toString());
	}

	/**
	 * Set value of Cursor
	 * @param cursor
	 */
	public final void setCursor(java.lang.String cursor)
	{
		setCursor(getContext(), cursor);
	}

	/**
	 * Set value of Cursor
	 * @param context
	 * @param cursor
	 */
	public final void setCursor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cursor)
	{
		getMendixObject().setValue(context, MemberNames.Cursor.toString(), cursor);
	}

	/**
	 * Set value of IncludeRemoteData
	 * @param includeremotedata
	 */
	public final merge.proxies.NullableBoolean getIncludeRemoteData()
	{
		return getIncludeRemoteData(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeRemoteData
	 */
	public final merge.proxies.NullableBoolean getIncludeRemoteData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.IncludeRemoteData.toString());
		if (obj == null)
			return null;

		return merge.proxies.NullableBoolean.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of IncludeRemoteData
	 * @param includeremotedata
	 */
	public final void setIncludeRemoteData(merge.proxies.NullableBoolean includeremotedata)
	{
		setIncludeRemoteData(getContext(), includeremotedata);
	}

	/**
	 * Set value of IncludeRemoteData
	 * @param context
	 * @param includeremotedata
	 */
	public final void setIncludeRemoteData(com.mendix.systemwideinterfaces.core.IContext context, merge.proxies.NullableBoolean includeremotedata)
	{
		if (includeremotedata != null)
			getMendixObject().setValue(context, MemberNames.IncludeRemoteData.toString(), includeremotedata.toString());
		else
			getMendixObject().setValue(context, MemberNames.IncludeRemoteData.toString(), null);
	}

	/**
	 * @return value of ModifiedAfter
	 */
	public final java.util.Date getModifiedAfter()
	{
		return getModifiedAfter(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedAfter
	 */
	public final java.util.Date getModifiedAfter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ModifiedAfter.toString());
	}

	/**
	 * Set value of ModifiedAfter
	 * @param modifiedafter
	 */
	public final void setModifiedAfter(java.util.Date modifiedafter)
	{
		setModifiedAfter(getContext(), modifiedafter);
	}

	/**
	 * Set value of ModifiedAfter
	 * @param context
	 * @param modifiedafter
	 */
	public final void setModifiedAfter(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date modifiedafter)
	{
		getMendixObject().setValue(context, MemberNames.ModifiedAfter.toString(), modifiedafter);
	}

	/**
	 * @return value of ModifiedBefore
	 */
	public final java.util.Date getModifiedBefore()
	{
		return getModifiedBefore(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedBefore
	 */
	public final java.util.Date getModifiedBefore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ModifiedBefore.toString());
	}

	/**
	 * Set value of ModifiedBefore
	 * @param modifiedbefore
	 */
	public final void setModifiedBefore(java.util.Date modifiedbefore)
	{
		setModifiedBefore(getContext(), modifiedbefore);
	}

	/**
	 * Set value of ModifiedBefore
	 * @param context
	 * @param modifiedbefore
	 */
	public final void setModifiedBefore(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date modifiedbefore)
	{
		getMendixObject().setValue(context, MemberNames.ModifiedBefore.toString(), modifiedbefore);
	}

	/**
	 * @return value of PageSize
	 */
	public final java.lang.Integer getPageSize()
	{
		return getPageSize(getContext());
	}

	/**
	 * @param context
	 * @return value of PageSize
	 */
	public final java.lang.Integer getPageSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageSize.toString());
	}

	/**
	 * Set value of PageSize
	 * @param pagesize
	 */
	public final void setPageSize(java.lang.Integer pagesize)
	{
		setPageSize(getContext(), pagesize);
	}

	/**
	 * Set value of PageSize
	 * @param context
	 * @param pagesize
	 */
	public final void setPageSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pagesize)
	{
		getMendixObject().setValue(context, MemberNames.PageSize.toString(), pagesize);
	}

	/**
	 * @return value of RemoteId
	 */
	public final java.lang.String getRemoteId()
	{
		return getRemoteId(getContext());
	}

	/**
	 * @param context
	 * @return value of RemoteId
	 */
	public final java.lang.String getRemoteId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RemoteId.toString());
	}

	/**
	 * Set value of RemoteId
	 * @param remoteid
	 */
	public final void setRemoteId(java.lang.String remoteid)
	{
		setRemoteId(getContext(), remoteid);
	}

	/**
	 * Set value of RemoteId
	 * @param context
	 * @param remoteid
	 */
	public final void setRemoteId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remoteid)
	{
		getMendixObject().setValue(context, MemberNames.RemoteId.toString(), remoteid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return queryParamsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.QueryParams that = (merge.proxies.QueryParams) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.QueryParams";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
