// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package merge.proxies;

public class RemoteData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject remoteDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Merge.RemoteData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RemoteData_Team("Merge.RemoteData_Team");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RemoteData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Merge.RemoteData"));
	}

	protected RemoteData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject remoteDataMendixObject)
	{
		if (remoteDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Merge.RemoteData", remoteDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Merge.RemoteData");

		this.remoteDataMendixObject = remoteDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RemoteData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static merge.proxies.RemoteData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return merge.proxies.RemoteData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static merge.proxies.RemoteData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new merge.proxies.RemoteData(context, mendixObject);
	}

	public static merge.proxies.RemoteData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return merge.proxies.RemoteData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RemoteData_Team
	 */
	public final merge.proxies.Team getRemoteData_Team() throws com.mendix.core.CoreException
	{
		return getRemoteData_Team(getContext());
	}

	/**
	 * @param context
	 * @return value of RemoteData_Team
	 */
	public final merge.proxies.Team getRemoteData_Team(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		merge.proxies.Team result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RemoteData_Team.toString());
		if (identifier != null)
			result = merge.proxies.Team.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RemoteData_Team
	 * @param remotedata_team
	 */
	public final void setRemoteData_Team(merge.proxies.Team remotedata_team)
	{
		setRemoteData_Team(getContext(), remotedata_team);
	}

	/**
	 * Set value of RemoteData_Team
	 * @param context
	 * @param remotedata_team
	 */
	public final void setRemoteData_Team(com.mendix.systemwideinterfaces.core.IContext context, merge.proxies.Team remotedata_team)
	{
		if (remotedata_team == null)
			getMendixObject().setValue(context, MemberNames.RemoteData_Team.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RemoteData_Team.toString(), remotedata_team.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return remoteDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final merge.proxies.RemoteData that = (merge.proxies.RemoteData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Merge.RemoteData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
